###

GET http://localhost:3000/gethour

###

GET http://localhost:3000/startcollecter

###

POST http://localhost:3000/modificarval
Content-Type: application/json

{
    "hsluz": 0,
    "riego": 0,
    "ventilacion": 3
}

###

GET http://localhost:3000/toexcel
