###

GET http://192.168.202.48:3000/gethour

###

GET http://localhost:3000/startcollecter

###

POST http://192.168.202.48:3000/modificarval
Content-Type: application/json

{
    "hsluz": 3,
    "riego": 3,
    "ventilacion": 3
}

###

GET http://192.168.202.48:3000/toexcel
